// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrxlr5XIGbegVy3_MLCq9J9DXr0BIdbaA',
    appId: '1:303926207281:web:5a82319edaf0e1349f4610',
    messagingSenderId: '303926207281',
    projectId: 'sol-2024-iitk',
    authDomain: 'sol-2024-iitk.firebaseapp.com',
    storageBucket: 'sol-2024-iitk.appspot.com',
    measurementId: 'G-JMQJRTLVQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxjBeCYNv_TbuQq5ejJ1J6oXBfx0DPcfA',
    appId: '1:303926207281:android:1e1b56d9ec21618a9f4610',
    messagingSenderId: '303926207281',
    projectId: 'sol-2024-iitk',
    storageBucket: 'sol-2024-iitk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9O2QKGecV__vj7CoRZ6wiwOklfEE47EE',
    appId: '1:303926207281:ios:6000316239ad38bc9f4610',
    messagingSenderId: '303926207281',
    projectId: 'sol-2024-iitk',
    storageBucket: 'sol-2024-iitk.appspot.com',
    iosBundleId: 'com.example.gdsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9O2QKGecV__vj7CoRZ6wiwOklfEE47EE',
    appId: '1:303926207281:ios:2212518f6e86f71a9f4610',
    messagingSenderId: '303926207281',
    projectId: 'sol-2024-iitk',
    storageBucket: 'sol-2024-iitk.appspot.com',
    iosBundleId: 'com.example.gdsc.RunnerTests',
  );
}
